name: stroke-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn==1.5.2
      - matplotlib
      - joblib