name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install mlflow==2.19.0

      - name: Run MLflow Project
        shell: bash -l {0}
        working-directory: MLProject
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          mlflow run .